# Generated by Django 2.1.5 on 2019-01-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='link_amazon',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('SF', 'Science Fiction'), ('F', 'Fantasy'), ('Myt', 'Mythology'), ('Ad', 'Adventure'), ('Mys', 'Mystery'), ('Dr', 'Drama'), ('Rom', 'Romance'), ('Hor', 'Horror'), ('Com', 'Comdey'), ('Th', 'Thriller'), ('Dy', 'Dystopia')], default='SF', max_length=3),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.CharField(default='unknown author', max_length=100),
        ),
    ]
